language: csharp

mono: 5.2.0
dotnet: 2.1
dist: trusty


install:
  - nuget install xunit.runner.console -version 2.2.0
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore Contextos/ControleOrcamento.Contexto.Domain
  - dotnet restore Contextos/ControleOrcamento.ContextoBancario.Domain
  - dotnet restore Contextos/ControleOrcamento.ContextoClassificacao.Domain
  - dotnet restore Contextos/ControleOrcamento.ContextoLancamento.Domain
  - dotnet restore Contextos/ControleOrcamento.ContextoQuitacao.Domain
  - dotnet restore Contextos/ControleOrcamento.ContextoUsuario.Domain

  - dotnet restore Contextos/Testes/ControleOrcamento.Mocks.Teste
  - dotnet restore Contextos/Testes/ControleOrcamento.Contexto.Domain.Teste
  - dotnet restore Contextos/Testes/ControleOrcamento.ContextoBancario.Domain.Teste
  - dotnet restore Contextos/Testes/ControleOrcamento.ContextoClassificacao.Domain.Teste
  - dotnet restore Contextos/Testes/ControleOrcamento.ContextoLancamento.Domain.Teste
  - dotnet restore Contextos/Testes/ControleOrcamento.ContextoQuitacao.Domain.Teste
  - dotnet restore Contextos/Testes/ControleOrcamento.ContextoUsuario.Domain.Teste

script:
  # Run tests
  - dotnet test Contextos/Testes/ControleOrcamento.Mocks.Teste --configuration Release --framework netcoreapp2.1
  - dotnet test Contextos/Testes/ControleOrcamento.Contexto.Domain.Teste --configuration Release --framework netcoreapp2.1
  - dotnet test Contextos/Testes/ControleOrcamento.ContextoBancario.Domain.Teste --configuration Release --framework netcoreapp2.1
  - dotnet test Contextos/Testes/ControleOrcamento.ContextoClassificacao.Domain.Teste --configuration Release --framework netcoreapp2.1
  - dotnet test Contextos/Testes/ControleOrcamento.ContextoLancamento.Domain.Teste --configuration Release --framework netcoreapp2.1
  - dotnet test Contextos/Testes/ControleOrcamento.ContextoQuitacao.Domain.Teste --configuration Release --framework netcoreapp2.1
  - dotnet test Contextos/Testes/ControleOrcamento.ContextoUsuario.Domain.Teste --configuration Release --framework netcoreapp2.1
  # Restore dos projetos
  - dotnet msbuild /t:Restore /p:targetframework=netcoreapp2.1 /p:monobuild=1 Contextos/ControleOrcamento.Contexto.Domain
  - dotnet msbuild /t:Restore /p:targetframework=netcoreapp2.1 /p:monobuild=1 Contextos/ControleOrcamento.ContextoBancario.Domain
  - dotnet msbuild /t:Restore /p:targetframework=netcoreapp2.1 /p:monobuild=1 Contextos/ControleOrcamento.ContextoClassificacao.Domain
  - dotnet msbuild /t:Restore /p:targetframework=netcoreapp2.1 /p:monobuild=1 Contextos/ControleOrcamento.ContextoLancamento.Domain
  - dotnet msbuild /t:Restore /p:targetframework=netcoreapp2.1 /p:monobuild=1 Contextos/ControleOrcamento.ContextoQuitacao.Domain
  - dotnet msbuild /t:Restore /p:targetframework=netcoreapp2.1 /p:monobuild=1 Contextos/ControleOrcamento.ContextoUsuario.Domain